// train1-figma-MUI/src/features/property-map/components/PropertyMarker.tsx
import { useState, useCallback } from 'react';
import Box from '@mui/material/Box';
import Stack from '@mui/material/Stack';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import Chip from '@mui/material/Chip';
import CircularProgress from '@mui/material/CircularProgress';
import { m, AnimatePresence } from 'framer-motion';
import { Flame, Maximize, Building } from 'lucide-react';
import type { UnitItem, InquiryStatusCode } from '../types/PropertyMapModel';
import { PALETTE, GRADIENT, BORDER_RADIUS, SHADOW } from '../../../theme';
import { formatPrice } from '../../../utils/format/formatPrice';
import { unitInquiryMutationApi } from '../services/unitInquiryMutationApi';
import { showToast } from '../../../utils/toast';
import { UNIT_STATUS, UNIT_TYPE_ICONS } from '../constants/propertyMapStatus';
import { useAppSelector } from '../../../store';

const MotionBox = m(Box);

interface PropertyMarkerProps {
  property: UnitItem;
  projectId: number;
  hideArrow?: boolean;
}

const PropertyMarker = ({ property, projectId, hideArrow = false }: PropertyMarkerProps) => {
  const {
    unitCode: code,
    isHot,
    unitTypeCode: type,
    areaLand: area,
    basePrice: listedPrice,
    loanPrice,
    statusCode,
    inquiryStatusCode: initialInquiryStatus,
  } = property;

  const { unitTypes, inquiryStatuses, unitStatuses } = useAppSelector((state) => state.propertyMap.masterData);

  const [inquiryStatus, setInquiryStatus] = useState<InquiryStatusCode | null | undefined>(
    initialInquiryStatus,
  );
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleRequestInfo = useCallback(async () => {
    setIsSubmitting(true);
    try {
      const response = await unitInquiryMutationApi.create(projectId, code);
      if (response.success) {
        setInquiryStatus(response.status);
        showToast.success('Yêu cầu đã được gửi thành công!');
      }
    } catch {
      showToast.error('Gửi yêu cầu thất bại. Vui lòng thử lại.');
    } finally {
      setIsSubmitting(false);
    }
  }, [projectId, code]);

  return (
    <AnimatePresence>
      <MotionBox
        key={property.id}
        initial={{ opacity: 0, scale: 0.5, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.5, y: 20 }}
        transition={{ type: 'spring', stiffness: 400, damping: 25 }}
        sx={{
          width: hideArrow ? '100%' : 220,
          maxWidth: hideArrow ? 360 : 220,
          display: 'flex',
          flexDirection: 'column',
          filter: `drop-shadow(${SHADOW.POPUP})`,
          transformOrigin: hideArrow ? 'center bottom' : 'bottom center',
        }}
      >
        {/* Header Section */}
        <Box
          sx={{
            backgroundColor: isHot ? PALETTE.ERROR : PALETTE.BACKGROUND_DEFAULT,
            borderRadius: `${BORDER_RADIUS.LARGE}px ${BORDER_RADIUS.LARGE}px 0 0`,
            p: isHot ? 0 : 1.5,
            pb: isHot ? 0 : 1,
            borderBottom: isHot ? 'none' : `1px solid ${PALETTE.BORDER}`,
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
          }}
        >
          <Stack
            direction="row"
            spacing={0.5}
            sx={{
              justifyContent: 'center',
              alignItems: 'center',
              p: isHot ? '8px 12px' : '6px 8px',
              backgroundColor: isHot ? 'transparent' : PALETTE.PRIMARY_LIGHT_BG,
              border: isHot ? 'none' : `1px solid ${PALETTE.PRIMARY}`,
              borderRadius: isHot ? 0 : `${BORDER_RADIUS.SMALL}px`,
              width: isHot ? '100%' : 'auto',
            }}
          >
            {isHot && <Flame size={16} color={PALETTE.SURFACE_LIGHT} />}
            <Typography
              sx={{
                fontWeight: 700,
                fontSize: '0.9375rem',
                color: isHot ? PALETTE.SURFACE_LIGHT : PALETTE.PRIMARY,
              }}
            >
              {code}
            </Typography>
          </Stack>
        </Box>

        {/* Body & Footer Section */}
        <Box
          sx={{
            backgroundColor: PALETTE.BACKGROUND_DEFAULT,
            borderRadius: `0 0 ${BORDER_RADIUS.LARGE}px ${BORDER_RADIUS.LARGE}px`,
            p: 1.5,
            pt: 1,
          }}
        >
          <Stack spacing={1}>
            {/* Details (Area & Type) */}
            <Stack
              direction="row"
              sx={{
                justifyContent: 'space-between',
                pt: '4px',
              }}
            >
              <Stack direction="row" spacing={0.5} sx={{ alignItems: 'center' }}>
                <Maximize size={16} color={PALETTE.TEXT_SECONDARY} />
                <Typography
                  sx={{
                    fontWeight: 500,
                    fontSize: '0.8125rem',
                    color: PALETTE.TEXT_PRIMARY,
                  }}
                >
                  {area ?? '—'}m²
                </Typography>
              </Stack>
              <Stack direction="row" spacing={0.5} sx={{ alignItems: 'center' }}>
                {type ? (
                  <Box
                    component="img"
                    src={UNIT_TYPE_ICONS[type] || '/icon_type/donlap.png'}
                    alt={unitTypes[type] || type}
                    sx={{
                      width: 16,
                      height: 16,
                      objectFit: 'contain',
                    }}
                  />
                ) : (
                  <Building size={16} color={PALETTE.TEXT_SECONDARY} />
                )}
                <Typography
                  sx={{
                    fontWeight: 500,
                    fontSize: '0.8125rem',
                    color: PALETTE.TEXT_SECONDARY,
                  }}
                >
                  {type ? (unitTypes[type] || type) : 'Chưa cập nhật'}
                </Typography>
              </Stack>
            </Stack>

            {/* Footer / Status Actions */}
            <Box sx={{ borderTop: `1px solid ${PALETTE.BORDER}`, pt: 1, mt: 0.5 }}>
              {statusCode === UNIT_STATUS.AVAILABLE ? (
                <Stack spacing={1}>
                  <Stack direction="row" sx={{ justifyContent: 'space-between', alignItems: 'center' }}>
                    <Typography
                      sx={{
                        fontWeight: 500,
                        fontSize: '0.8125rem',
                        color: PALETTE.TEXT_SECONDARY,
                      }}
                    >
                      Giá niêm yết:
                    </Typography>
                    <Typography
                      sx={{
                        fontWeight: 700,
                        fontSize: '0.8125rem',
                        color: PALETTE.PRIMARY,
                      }}
                    >
                      {listedPrice != null ? formatPrice(listedPrice) : 'Liên hệ'}
                    </Typography>
                  </Stack>
                  <Stack direction="row" sx={{ justifyContent: 'space-between', alignItems: 'center' }}>
                    <Typography
                      sx={{
                        fontWeight: 500,
                        fontSize: '0.8125rem',
                        color: PALETTE.TEXT_SECONDARY,
                      }}
                    >
                      Giá vay:
                    </Typography>
                    <Typography
                      sx={{
                        fontWeight: 700,
                        fontSize: '0.8125rem',
                        color: PALETTE.PRIMARY,
                      }}
                    >
                      {loanPrice != null ? formatPrice(loanPrice) : 'Đang cập nhật'}
                    </Typography>
                  </Stack>
                </Stack>
              ) : statusCode === UNIT_STATUS.SOLD ? (
                <Chip
                  label={statusCode ? (unitStatuses[statusCode] || 'Đã bán') : 'Đã bán'}
                  sx={{
                    width: '100%',
                    backgroundColor: PALETTE.ERROR_LIGHT,
                    color: PALETTE.ERROR,
                    fontWeight: 500,
                    fontSize: '0.6875rem',
                    borderRadius: `${BORDER_RADIUS.SMALL}px`,
                  }}
                />
              ) : inquiryStatus ? (
                <Typography
                  sx={{
                    fontWeight: 500,
                    fontStyle: 'italic',
                    fontSize: '0.8125rem',
                    color: PALETTE.TEXT_DISABLED,
                    textAlign: 'center',
                    py: 1,
                  }}
                >
                  {inquiryStatus ? (inquiryStatuses[inquiryStatus] || inquiryStatus) : ''}
                </Typography>
              ) : (
                <Stack spacing={1}>
                  <Typography
                    sx={{
                      fontWeight: 500,
                      fontStyle: 'italic',
                      fontSize: '0.8125rem',
                      color: PALETTE.TEXT_DISABLED,
                      textAlign: 'center',
                    }}
                  >
                    Quỹ hàng ẩn
                  </Typography>
                  <Button
                    fullWidth
                    variant="contained"
                    disabled={isSubmitting}
                    onClick={handleRequestInfo}
                    sx={{
                      background: GRADIENT.PRIMARY,
                      borderRadius: `${BORDER_RADIUS.MEDIUM}px`,
                      fontWeight: 600,
                      fontSize: '0.8125rem',
                      color: PALETTE.SURFACE_LIGHT,
                      py: '7px',
                      boxShadow: 'none',
                      '&:hover': {
                        background: GRADIENT.PRIMARY,
                        opacity: 0.9,
                        boxShadow: 'none',
                      },
                      '&.Mui-disabled': {
                        background: PALETTE.GREY_LIGHT,
                      },
                    }}
                  >
                    {isSubmitting ? (
                      <CircularProgress size={18} sx={{ color: PALETTE.SURFACE_LIGHT }} />
                    ) : (
                      'Xin thông tin'
                    )}
                  </Button>
                </Stack>
              )}
            </Box>
          </Stack>
        </Box>

        {/* Bottom arrow / triangle */}
        {!hideArrow && (
          <Box
            sx={{
              display: 'flex',
              justifyContent: 'center',
            }}
          >
            <Box
              component="svg"
              viewBox="0 0 200 18"
              sx={{
                width: '100%',
                height: 18,
                display: 'block',
              }}
            >
              <path d="M0,0 L90,0 L100,18 L110,0 L200,0" fill={PALETTE.BACKGROUND_DEFAULT} />
            </Box>
          </Box>
        )}
      </MotionBox>
    </AnimatePresence>
  );
};

export default PropertyMarker;

// MBQC - Angular/src/app/features/property-map/components/property-marker/property-marker.component.ts
import { Component, ChangeDetectionStrategy, inject, Input, Output, EventEmitter, computed, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PropertyMapStateService } from '../../services/property-map-state.service';
import { PropertyMapService } from '../../services/property-map.service';
import { ToastService } from '../../../../core/services/toast.service';
import { FormatPricePipe } from '../../pipes/format-price.pipe';
import { MasterDataLabelPipe } from '../../pipes/master-data-label.pipe';
import { CONFIG } from '../../../../constants/config.constant';
import type { UnitItem } from '../../models/property-map.model';
import { UNIT_TYPE_ICONS } from '../../constants/property-map.constant';

@Component({
  selector: 'app-property-marker',
  standalone: true,
  imports: [CommonModule, FormatPricePipe, MasterDataLabelPipe],
  templateUrl: './property-marker.component.html',
  styleUrls: ['./property-marker.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PropertyMarkerComponent {
  @Input({ required: true }) unit!: UnitItem;
  @Input() hideArrow = false;
  @Output() close = new EventEmitter<void>();

  private readonly state = inject(PropertyMapStateService);
  private readonly api = inject(PropertyMapService);
  private readonly toast = inject(ToastService);

  readonly projectId = CONFIG.DEFAULT_PROJECT_ID;
  readonly isSubmitting = signal(false);
  readonly icons = UNIT_TYPE_ICONS;

  readonly masterData = this.state.masterData;

  handleClose() {
    this.close.emit();
  }

  handleInquiry(event: MouseEvent) {
    event.stopPropagation();
    if (this.isSubmitting() || this.unit.inquiryStatusCode) return;

    this.isSubmitting.set(true);
    this.api.createInquiry(this.projectId, this.unit.unitCode).subscribe({
      next: (res) => {
        this.isSubmitting.set(false);
        if (res.success) {
          this.toast.success('Yêu cầu đã được gửi thành công!');
          // Update unit status locally
          this.unit.inquiryStatusCode = res.status;
          const newStatusName = res.inquiryStatusName || res.statusName;
          if (newStatusName) {
            this.unit.inquiryStatusName = newStatusName;
          }
          this.state.units.update(units =>
            units.map(u => u.unitCode === this.unit.unitCode
              ? { ...u, inquiryStatusCode: res.status, inquiryStatusName: newStatusName || u.inquiryStatusName }
              : u
            )
          );
        } else {
          this.toast.error('Gửi yêu cầu thất bại. Vui lòng thử lại.');
        }
      },
      error: () => {
        this.isSubmitting.set(false);
        this.toast.error('Gửi yêu cầu thất bại. Vui lòng thử lại.');
      }
    });
  }
}

<div 
  class="popup-card-wrapper"
  [class.hide-arrow]="hideArrow"
>
  <!-- Header Section -->
  <div class="popup-header-block" [class.is-hot]="unit.isHot && unit.statusCode !== 'SOLD'">
    <div class="code-badge-container" [class.is-hot]="unit.isHot && unit.statusCode !== 'SOLD'">
      @if (unit.isHot && unit.statusCode !== 'SOLD') {
        <span class="flame-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-flame"><path d="M8.5 14.5A2.5 2.5 0 0 0 11 12c0-1.38-.5-2-1-3-1.072-2.143-.224-4.054 2-6 .5 2.5 2 4.9 4 6.5 2 1.6 3 3.5 3 5.5a7 7 0 1 1-14 0c0-1.153.433-2.294 1-3a2.5 2.5 0 0 0 2.5 2.5z"/></svg>
        </span>
      }
      <span class="badge-text">{{ unit.unitCode }}</span>
    </div>
  </div>

  <!-- Body Section -->
  <div class="popup-body-block">
    <div class="details-row">
      <!-- Area land -->
      <div class="detail-col">
        <span class="detail-icon">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-maximize"><path d="M15 3h6v6"/><path d="M9 21H3v-6"/><path d="M21 3l-7 7"/><path d="M3 21l7-7"/></svg>
        </span>
        <span class="detail-text">{{ unit.areaLand ?? '—' }}m²</span>
      </div>

      <!-- Unit Type Icon & Label -->
      <div class="detail-col">
        @if (unit.unitTypeCode) {
          <img 
            [src]="icons[unit.unitTypeCode] || '/icon_type/donlap.png'" 
            [alt]="(unit.unitTypeCode | masterDataLabel:'unitTypes':masterData())"
            class="type-icon" 
          />
        } @else {
          <span class="detail-icon">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-building"><rect width="16" height="20" x="4" y="2" rx="2" ry="2"/><path d="M9 22v-4h6v4"/><path d="M8 6h.01"/><path d="M16 6h.01"/><path d="M8 10h.01"/><path d="M16 10h.01"/><path d="M8 14h.01"/><path d="M16 14h.01"/></svg>
          </span>
        }
        <span class="detail-text truncate-text" [title]="(unit.unitTypeCode | masterDataLabel:'unitTypes':masterData())">{{ (unit.unitTypeCode | masterDataLabel:'unitTypes':masterData()) }}</span>
      </div>
    </div>

    <!-- Divider and Actions -->
    <div class="actions-section">
      <!-- 1. Available state -->
      @if (unit.statusCode === 'AVAILABLE') {
        <div class="price-stack">
          <div class="price-item">
            <span class="price-label">Giá niêm yết:</span>
            <span class="price-val">{{ unit.basePrice != null ? (unit.basePrice | formatPrice) : 'Liên hệ' }}</span>
          </div>
          <div class="price-item">
            <span class="price-label">Giá vay:</span>
            <span class="price-val">{{ unit.loanPrice != null ? (unit.loanPrice | formatPrice) : 'Đang cập nhật' }}</span>
          </div>
        </div>
      }

      <!-- 2. Sold state -->
      @else if (unit.statusCode === 'SOLD') {
        <div class="sold-chip">
          {{ (unit.statusCode | masterDataLabel:'unitStatuses':masterData()) }}
        </div>
      }

      <!-- 3. Inquiry status active -->
      @else if (unit.inquiryStatusCode) {
        <div class="inquiry-status-text">
          {{ (unit.inquiryStatusCode | masterDataLabel:'inquiryStatuses':masterData():unit.inquiryStatusName) }}
        </div>
      }

      <!-- 4. Hidden state without inquiry -->
      @else {
        <div class="hidden-stack">
          <div class="hidden-text">Quỹ hàng ẩn</div>
          <button 
            type="button" 
            class="inquiry-btn" 
            [disabled]="isSubmitting()"
            (click)="handleInquiry($event)"
          >
            @if (isSubmitting()) {
              <span class="inquiry-spinner"></span>
            } @else {
              Xin thông tin
            }
          </button>
        </div>
      }
    </div>
  </div>

  <!-- Bottom Arrow Triangle SVG -->
  @if (!hideArrow) {
    <div class="popup-arrow-wrapper">
      <svg viewBox="0 0 200 18" class="arrow-svg">
        <path d="M0,0 L90,0 L100,18 L110,0 L200,0" fill="var(--palette-bg-default)" />
      </svg>
    </div>
  }
</div>
