// train1-figma-MUI/src/features/property-map/components/CanvasMarkerLayer.tsx
import { useEffect, useRef } from 'react';
import { useMap } from 'react-leaflet';
import L from 'leaflet';
import { convertPercentToLatLng, convertPdfCoorsToLatLng } from '../utils/mapUtils';
import type { UnitItem } from '../types/PropertyMapModel';
import { drawPropertyMarker, MARKER_WIDTH, clearMarkerCache } from '../utils/canvasMarkerRenderer';
import { useAppSelector } from '@/store';

interface CanvasMarkerLayerProps {
  properties: UnitItem[];
  selectedId: string | null;
  onSelectProperty: (id: string | null) => void;
  mapWidth: number;
  mapHeight: number;
  mapMaxZoom: number;
  mapScale: number;
}

interface BBox {
  id: string;
  left: number;
  top: number;
  right: number;
  bottom: number;
}

const CanvasMarkerLayer = ({
  properties,
  selectedId,
  onSelectProperty,
  mapWidth,
  mapHeight,
  mapMaxZoom,
  mapScale,
}: CanvasMarkerLayerProps) => {
  const map = useMap();
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const bboxesRef = useRef<BBox[]>([]);
  const hoveredIdRef = useRef<string | null>(null);

  const mapData = useAppSelector((state) => state.propertyMap.mapData);

  const propsRef = useRef({ properties, selectedId, onSelectProperty, mapData, mapWidth, mapHeight, mapMaxZoom, mapScale });
  useEffect(() => {
    propsRef.current = { properties, selectedId, onSelectProperty, mapData, mapWidth, mapHeight, mapMaxZoom, mapScale };
  }, [properties, selectedId, onSelectProperty, mapData, mapWidth, mapHeight, mapMaxZoom, mapScale]);

  useEffect(() => {
    const canvas = L.DomUtil.create('canvas', 'leaflet-zoom-animated') as HTMLCanvasElement;
    canvas.style.pointerEvents = 'none';
    canvas.style.zIndex = '400'; // Đặt lớp Canvas nằm trên đè lên TileLayer hình ảnh mặt bằng

    const pane = map.getPane('overlayPane');
    if (!pane) return;
    pane.appendChild(canvas);
    canvasRef.current = canvas;

    const redraw = () => {
      const size = map.getSize();
      const topLeft = map.containerPointToLayerPoint([0, 0]);
      L.DomUtil.setPosition(canvas, topLeft);

      const dpr = window.devicePixelRatio || 1;

      if (canvas.width !== size.x * dpr || canvas.height !== size.y * dpr) {
        canvas.width = size.x * dpr;
        canvas.height = size.y * dpr;
        canvas.style.width = `${size.x}px`;
        canvas.style.height = `${size.y}px`;
      }

      const ctx = canvas.getContext('2d');
      if (!ctx) return;

      ctx.clearRect(0, 0, canvas.width, canvas.height);
      ctx.save();
      ctx.scale(dpr, dpr);

      const { properties: currentProps, selectedId: currentSelected, mapData: currentMapData } = propsRef.current;
      const bboxes: BBox[] = [];

      const unselected = currentProps.filter(p => String(p.id || p.unitCode) !== currentSelected);
      const selected = currentProps.find(p => String(p.id || p.unitCode) === currentSelected);

      const drawProp = (property: UnitItem, isSelected: boolean) => {
        const propertyId = String(property.id || property.unitCode);
        const latLng = currentMapData
          ? convertPdfCoorsToLatLng(
            property.x || 0,
            property.y || 0,
            currentMapData.dpi,
            property.xPixel,
            property.yPixel,
            propsRef.current.mapScale
          )
          : convertPercentToLatLng(property.x || 0, property.y || 0, propsRef.current.mapWidth, propsRef.current.mapHeight, propsRef.current.mapScale);

        // Quy đổi tọa độ LatLng sang tọa độ Pixel thực tế trên Frame hiển thị của Container Web
        const layerPoint = map.latLngToLayerPoint(latLng as L.LatLngTuple);
        const x = layerPoint.x - topLeft.x;
        const y = layerPoint.y - topLeft.y;

        if (import.meta.env.DEV && property.unitCode === 'VK1-18') {
          console.log(`[DEBUG VK1-18] x=${property.x}, y=${property.y}, xPixel=${property.xPixel}, yPixel=${property.yPixel}, px=${x}, py=${y}`);
        }

        const isHovered = propertyId === hoveredIdRef.current;

        // Vẽ khối card căn hộ
        const height = drawPropertyMarker(ctx, property, x, y, isSelected || isHovered);

        // Lưu trữ vùng bấm (Bounding Box) phục vụ cho Hit Testing (Click/Hover chuột)
        bboxes.push({
          id: propertyId,
          left: x - MARKER_WIDTH / 2,
          top: y - height,
          right: x + MARKER_WIDTH / 2,
          bottom: y
        });
      };

      unselected.forEach(p => drawProp(p, false));
      if (selected) {
        drawProp(selected, true);
      }

      bboxesRef.current = bboxes;
      ctx.restore();
    };

    let rAF: number;
    const requestRedraw = () => {
      cancelAnimationFrame(rAF);
      rAF = requestAnimationFrame(redraw);
    };

    map.on('viewreset move resize zoom', requestRedraw);
    requestRedraw();

    // Xử lý sự kiện Hover chuột di chuyển trên bản đồ phẳng
    const handleMouseMove = (e: L.LeafletMouseEvent) => {
      const { x, y } = e.containerPoint;
      let foundId: string | null = null;
      for (let i = bboxesRef.current.length - 1; i >= 0; i--) {
        const bbox = bboxesRef.current[i];
        if (x >= bbox.left && x <= bbox.right && y >= bbox.top && y <= bbox.bottom) {
          foundId = bbox.id;
          break;
        }
      }

      if (hoveredIdRef.current !== foundId) {
        hoveredIdRef.current = foundId;
        map.getContainer().style.cursor = foundId ? 'pointer' : '';
        
        requestRedraw();
      }
    };

    // Xử lý sự kiện Click chuột chọn căn trên bản đồ phẳng
    const handleClick = (e: L.LeafletMouseEvent) => {
      const { x, y } = e.containerPoint;
      let foundId: string | null = null;
      
      for (let i = bboxesRef.current.length - 1; i >= 0; i--) {
        const bbox = bboxesRef.current[i];
        if (x >= bbox.left && x <= bbox.right && y >= bbox.top && y <= bbox.bottom) {
          foundId = bbox.id;
          break;
        }
      }

      const { selectedId, onSelectProperty } = propsRef.current;
      if (foundId) {
        onSelectProperty(foundId === selectedId ? null : foundId);
        L.DomEvent.stopPropagation(e);
      } else {
        if (selectedId !== null) {
          onSelectProperty(null);
        }
      }
    };

    const handleIconsLoaded = () => {
      requestRedraw();
    };

    map.on('mousemove', handleMouseMove);
    map.on('click', handleClick);
    window.addEventListener('unit-icons-loaded', handleIconsLoaded);

    return () => {
      cancelAnimationFrame(rAF);
      map.off('viewreset move resize zoom', requestRedraw);
      map.off('mousemove', handleMouseMove);
      map.off('click', handleClick);
      window.removeEventListener('unit-icons-loaded', handleIconsLoaded);
      pane.removeChild(canvas);
      map.getContainer().style.cursor = '';
      clearMarkerCache();
    };
  }, [map]);

  useEffect(() => {
    map.fire('move');
  }, [properties, selectedId, map]);

  return null;
};

export default CanvasMarkerLayer;

// MBQC - Angular/src/app/features/property-map/components/canvas-marker-layer/canvas-marker-layer.component.ts
import { Component, AfterViewInit, OnDestroy, Input, Output, EventEmitter, inject, effect, OnChanges, SimpleChanges, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import * as L from 'leaflet';
import { PropertyMapStateService } from '../../services/property-map-state.service';
import type { UnitItem } from '../../models/property-map.model';
import { drawPropertyMarker, MARKER_WIDTH, clearMarkerCache } from '../../utils/canvas-marker-renderer.util';
import { convertPercentToLatLng, convertPdfCoorsToLatLng } from '../../utils/map.util';

interface BBox {
  id: string;
  left: number;
  top: number;
  right: number;
  bottom: number;
}

@Component({
  selector: 'app-canvas-marker-layer',
  standalone: true,
  imports: [CommonModule],
  template: '', // No template needed as it appends directly to Leaflet overlayPane
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class CanvasMarkerLayerComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input({ required: true }) map!: L.Map;
  @Input() properties: UnitItem[] = [];
  @Input() selectedId: string | null = null;
  @Input() mapWidth!: number;
  @Input() mapHeight!: number;
  @Input() mapMaxZoom!: number;
  @Input() mapScale: number = 1;

  @Output() selectProperty = new EventEmitter<string | null>();

  private readonly state = inject(PropertyMapStateService);

  private canvas: HTMLCanvasElement | null = null;
  private bboxes: BBox[] = [];
  private hoveredId: string | null = null;
  private rAFId = 0;

  constructor() {
    effect(() => {
      // Re-trigger redraw when global mapData changes
      const data = this.state.mapData();
      if (data) {
        this.requestRedraw();
      }
    });
  }

  ngOnChanges(changes: SimpleChanges) {
    if (this.canvas) {
      this.requestRedraw();
    }
  }

  ngAfterViewInit() {
    if (!this.map) return;

    // Create Leaflet overlay canvas
    this.canvas = L.DomUtil.create('canvas', 'leaflet-zoom-animated') as HTMLCanvasElement;
    this.canvas.style.pointerEvents = 'none';
    this.canvas.style.zIndex = '400';

    const pane = this.map.getPane('overlayPane');
    if (pane) {
      pane.appendChild(this.canvas);
    }

    // Leaflet map events
    this.map.on('viewreset move resize zoom', this.requestRedraw, this);

    // Hit Testing Events on the map
    this.map.on('mousemove', this.handleMouseMove, this);
    this.map.on('click', this.handleClick, this);

    // Preload icons listener
    window.addEventListener('unit-icons-loaded', this.handleIconsLoaded);

    this.requestRedraw();
  }

  ngOnDestroy() {
    cancelAnimationFrame(this.rAFId);

    if (this.map) {
      this.map.off('viewreset move resize zoom', this.requestRedraw, this);
      this.map.off('mousemove', this.handleMouseMove, this);
      this.map.off('click', this.handleClick, this);
      this.map.getContainer().style.cursor = '';
    }

    window.removeEventListener('unit-icons-loaded', this.handleIconsLoaded);

    if (this.canvas && this.canvas.parentNode) {
      this.canvas.parentNode.removeChild(this.canvas);
    }

    clearMarkerCache();
  }

  private handleIconsLoaded = () => {
    this.requestRedraw();
  };

  private requestRedraw = () => {
    cancelAnimationFrame(this.rAFId);
    this.rAFId = requestAnimationFrame(() => this.redraw());
  };

  private redraw() {
    if (!this.canvas || !this.map) return;

    const size = this.map.getSize();

    // Guard: if container hasn't been laid out yet, skip and schedule retry
    if (size.x === 0 || size.y === 0) {
      cancelAnimationFrame(this.rAFId);
      this.rAFId = requestAnimationFrame(() => this.redraw());
      return;
    }

    const topLeft = this.map.containerPointToLayerPoint([0, 0]);
    L.DomUtil.setPosition(this.canvas, topLeft);

    const dpr = window.devicePixelRatio || 1;

    // Ensure canvas dimensions matches pixel density
    if (this.canvas.width !== size.x * dpr || this.canvas.height !== size.y * dpr) {
      this.canvas.width = size.x * dpr;
      this.canvas.height = size.y * dpr;
      this.canvas.style.width = `${size.x}px`;
      this.canvas.style.height = `${size.y}px`;
    }

    const ctx = this.canvas.getContext('2d');
    if (!ctx) return;

    ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
    ctx.save();
    ctx.scale(dpr, dpr);

    const bboxes: BBox[] = [];
    const mapData = this.state.mapData();

    const unselected = this.properties.filter(p => String(p.id || p.unitCode) !== this.selectedId);
    const selected = this.properties.find(p => String(p.id || p.unitCode) === this.selectedId);

    const drawProp = (property: UnitItem, isSelected: boolean) => {
      const propertyId = String(property.id || property.unitCode);
      const latLng = mapData
        ? convertPdfCoorsToLatLng(
            property.x || 0,
            property.y || 0,
            mapData.dpi,
            property.xPixel,
            property.yPixel,
            this.mapScale
          )
        : convertPercentToLatLng(
            property.x || 0,
            property.y || 0,
            this.mapWidth,
            this.mapHeight,
            this.mapScale
          );

      const layerPoint = this.map.latLngToLayerPoint(latLng);
      const x = layerPoint.x - topLeft.x;
      const y = layerPoint.y - topLeft.y;

      const isHovered = propertyId === this.hoveredId;

      const height = drawPropertyMarker(ctx, x, y, property, isSelected || isHovered);

      bboxes.push({
        id: propertyId,
        left: x - MARKER_WIDTH / 2,
        top: y - height,
        right: x + MARKER_WIDTH / 2,
        bottom: y
      });
    };

    unselected.forEach(p => drawProp(p, false));
    if (selected) {
      drawProp(selected, true);
    }

    this.bboxes = bboxes;
    ctx.restore();
  }

  private handleMouseMove(e: L.LeafletMouseEvent) {
    const { x, y } = e.containerPoint;
    let foundId: string | null = null;

    for (let i = this.bboxes.length - 1; i >= 0; i--) {
      const bbox = this.bboxes[i];
      if (x >= bbox.left && x <= bbox.right && y >= bbox.top && y <= bbox.bottom) {
        foundId = bbox.id;
        break;
      }
    }

    if (this.hoveredId !== foundId) {
      this.hoveredId = foundId;
      this.map.getContainer().style.cursor = foundId ? 'pointer' : '';
      this.requestRedraw();
    }
  }

  private handleClick(e: L.LeafletMouseEvent) {
    const { x, y } = e.containerPoint;
    let foundId: string | null = null;

    for (let i = this.bboxes.length - 1; i >= 0; i--) {
      const bbox = this.bboxes[i];
      if (x >= bbox.left && x <= bbox.right && y >= bbox.top && y <= bbox.bottom) {
        foundId = bbox.id;
        break;
      }
    }

    if (foundId) {
      this.selectProperty.emit(foundId === this.selectedId ? null : foundId);
      L.DomEvent.stopPropagation(e);
    } else {
      if (this.selectedId !== null) {
        this.selectProperty.emit(null);
      }
    }
  }
}
