// MBQC - Angular/src/app/components/common/footer/footer.component.ts
import { Component, ChangeDetectionStrategy, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FooterComponent {
  private readonly sanitizer = inject(DomSanitizer);

  readonly menuItems = ['Giới thiệu', 'Dự án', 'Liên hệ'];

  readonly socialLinks = [
    { 
      id: 'fb', 
      name: 'Facebook', 
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-facebook"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/></svg>' 
    },
    { 
      id: 'yt', 
      name: 'Youtube', 
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-youtube"><path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17z"/><path d="m10 15 5-3-5-3z"/></svg>' 
    },
    { 
      id: 'ig', 
      name: 'Instagram', 
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-instagram"><rect width="20" height="20" x="2" y="2" rx="5" ry="5"/><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"/><line x1="17.5" x2="17.51" y1="6.5" y2="6.5"/></svg>' 
    },
    { 
      id: 'tw', 
      name: 'Twitter', 
      icon: '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-twitter"><path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z"/></svg>' 
    },
  ];

  readonly mapUrl = 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.811559902302!2d105.93818311540199!3d20.985929986021655!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135a1a1f5928f09%3A0x633d2fc1a11db9d9!2zVmluaG9tZXMgT2NlYW4gUGFyayBHaWEgTMOibQ!5e0!3m2!1svi!2s!4v1689000000000!5m2!1svi!2s';

  readonly safeMapUrl: SafeResourceUrl = this.sanitizer.bypassSecurityTrustResourceUrl(this.mapUrl);
}

<footer class="footer-block">
  <div class="footer-container">
    <div class="footer-columns">
      <!-- Company Info -->
      <div class="company-info-column">
        <div class="company-logo-row">
          <img src="/logo-white.png" alt="Realestate Company Logo" class="company-logo-img" />
          <p class="company-tagline">
            Nền tảng công nghệ tiên phong & dẫn đầu lĩnh vực kinh doanh bất động sản tại Việt Nam
          </p>
        </div>

        <div class="company-contact-list">
          <div class="contact-item">
            <span class="contact-icon">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-phone"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/></svg>
            </span>
            <span class="contact-text">0972 72 9999</span>
          </div>

          <div class="contact-item">
            <span class="contact-icon">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-mail"><rect width="20" height="16" x="2" y="4" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/></svg>
            </span>
            <span class="contact-text">Contact&#64;gmail.com</span>
          </div>

          <div class="contact-item align-top">
            <span class="contact-icon mt-4">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-map-pin"><path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="3"/></svg>
            </span>
            <span class="contact-text">SB24-36, Sao Biển 24, KĐT Vinhomes Ocean Park, Xã Gia Lâm, TP Hà Nội, Việt Nam</span>
          </div>
        </div>
      </div>

      <!-- Links and Connect Column -->
      <div class="links-and-connect">
        <div class="flex-sub-columns">
          <!-- Links Section -->
          <div class="section-menu">
            <h3 class="section-title">Danh mục</h3>
            <div class="menu-list">
              @for (item of menuItems; track item) {
                <a class="menu-link">- {{ item }}</a>
              }
            </div>
          </div>

          <!-- Socials Section -->
          <div class="section-socials">
            <h3 class="section-title">Kết nối</h3>
            <div class="social-icons">
              @for (social of socialLinks; track social.id) {
                <div class="social-circle" [title]="social.name">
                  <span class="social-icon" [innerHTML]="social.icon"></span>
                </div>
              }
            </div>
          </div>
        </div>

        <!-- Google Maps Embed -->
        <div class="map-embed-wrapper">
          <iframe 
            [src]="safeMapUrl"
            width="100%" 
            height="100%" 
            style="border: 0;"
            title="Vinhomes Ocean Park Map Location"
            loading="lazy"
            referrerpolicy="no-referrer-when-downgrade"
          ></iframe>
        </div>
      </div>
    </div>

    <!-- Copyright -->
    <div class="footer-copyright-row">
      <p class="copyright-text">© 2026 - Realestate. All rights reserved.</p>
    </div>
  </div>
</footer>

// train1-figma/src/components/Layout/Footer.tsx
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import { motion } from 'framer-motion';
import { Phone, Mail, MapPin } from 'lucide-react';
import FacebookIcon from '@mui/icons-material/Facebook';
import YouTubeIcon from '@mui/icons-material/YouTube';
import InstagramIcon from '@mui/icons-material/Instagram';
import TwitterIcon from '@mui/icons-material/Twitter';
import { PALETTE, GRADIENT } from '../../theme';

const MotionBox = motion(Box);

const Footer = () => {
  return (
    <Box
      component="footer"
      sx={{
        display: 'flex',
        flexDirection: 'column',
        gap: 3,
        background: GRADIENT.PRIMARY,
        px: { xs: 1.5, md: 4 },
        py: { xs: 3, md: 4 },
      }}
    >
      <Box
        sx={{
          display: 'flex',
          justifyContent: 'space-between',
          flexDirection: { xs: 'column', md: 'row' },
          alignItems: 'flex-start',
          gap: 4,
          textAlign: 'left',
        }}
      >
        {/* Company info */}
        <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: 3, maxWidth: { xs: '100%', md: 373 } }}>
          <Box sx={{ display: 'flex', flexDirection: 'row', alignItems: 'center', gap: 2, justifyContent: 'flex-start' }}>
            <Box
              component="img"
              src="/logo-white.png"
              alt="Realestate Logo"
              sx={{ width: 60, height: 60, objectFit: 'contain' }}
            />
            <Typography
              sx={{
                fontWeight: 600,
                fontSize: '1rem',
                lineHeight: '24px',
                color: PALETTE.BACKGROUND_PAPER,
              }}
            >
              Nền tảng công nghệ tiên phong & dẫn đầu lĩnh vực kinh doanh bất động sản tại Việt Nam
            </Typography>
          </Box>

          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1.5, alignItems: 'flex-start' }}>
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
              <Phone size={16} color={PALETTE.BACKGROUND_DEFAULT} />
              <Typography
                sx={{
                  fontWeight: 500,
                  fontSize: '0.8125rem',
                  lineHeight: '26px',
                  color: PALETTE.BACKGROUND_DEFAULT,
                }}
              >
                0972 72 9999
              </Typography>
            </Box>
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
              <Mail size={16} color={PALETTE.BACKGROUND_DEFAULT} />
              <Typography
                sx={{
                  fontWeight: 500,
                  fontSize: '0.8125rem',
                  lineHeight: '26px',
                  color: PALETTE.BACKGROUND_DEFAULT,
                }}
              >
                Contact@gmail.com
              </Typography>
            </Box>
            <Box sx={{ display: 'flex', alignItems: 'flex-start', gap: 1, pt: 0.5 }}>
              <Box sx={{ display: 'flex', mt: 0.5 }}>
                <MapPin size={16} color={PALETTE.BACKGROUND_DEFAULT} />
              </Box>
              <Typography
                sx={{
                  fontWeight: 500,
                  fontSize: '0.8125rem',
                  lineHeight: '21px',
                  color: PALETTE.BACKGROUND_DEFAULT,
                  textAlign: 'left'
                }}
              >
                SB24-36, Sao Biển 24, KĐT Vinhomes Ocean Park, Xã Gia Lâm, TP Hà Nội, Việt Nam
              </Typography>
            </Box>
          </Box>
        </Box>

        <Box sx={{ display: 'flex', flexDirection: { xs: 'column', md: 'row' }, gap: { xs: 4, md: 8 }, flex: 1, justifyContent: 'flex-end', width: '100%' }}>
          <Box sx={{ display: 'flex', flexDirection: { xs: 'column', sm: 'row' }, gap: { xs: 4, md: 8 }, justifyContent: 'flex-start' }}>
            {/* Menu */}
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2, alignItems: 'flex-start' }}>
              <Typography
                sx={{
                  fontWeight: 600,
                  fontSize: '1.125rem',
                  color: PALETTE.SURFACE_LIGHT,
                }}
              >
                Danh mục
              </Typography>
              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1, alignItems: 'flex-start' }}>
                {['Giới thiệu', 'Dự án', 'Liên hệ'].map((item) => (
                  <Typography
                    key={item}
                    sx={{
                      fontWeight: 500,
                      fontSize: '0.9375rem',
                      color: PALETTE.BACKGROUND_DEFAULT,
                      cursor: 'pointer',
                      '&:hover': { opacity: 0.8 },
                    }}
                  >
                    - {item}
                  </Typography>
                ))}
              </Box>
            </Box>

            {/* Social */}
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2, alignItems: 'flex-start' }}>
              <Typography
                sx={{
                  fontWeight: 600,
                  fontSize: '1.125rem',
                  color: PALETTE.SURFACE_LIGHT,
                }}
              >
                Kết nối
              </Typography>
              <Box sx={{ display: 'flex', gap: 2, justifyContent: 'flex-start' }}>
                {[
                  { id: 'fb', icon: <FacebookIcon sx={{ fontSize: 18, color: '#fff' }} /> },
                  { id: 'yt', icon: <YouTubeIcon sx={{ fontSize: 18, color: '#fff' }} /> },
                  { id: 'ig', icon: <InstagramIcon sx={{ fontSize: 18, color: '#fff' }} /> },
                  { id: 'tw', icon: <TwitterIcon sx={{ fontSize: 18, color: '#fff' }} /> }
                ].map((item) => (
                  <MotionBox
                    key={item.id}
                    sx={{
                      width: 36,
                      height: 36,
                      borderRadius: '50%',
                      backgroundColor: 'rgba(255,255,255,0.1)',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      cursor: 'pointer',
                    }}
                    whileHover={{ backgroundColor: 'rgba(255,255,255,0.3)', y: -3 }}
                    whileTap={{ scale: 0.9 }}
                  >
                    {item.icon}
                  </MotionBox>
                ))}
              </Box>
            </Box>
          </Box>

          {/* Map iframe */}
          <Box sx={{ width: { xs: '100%', md: 300 }, height: 200, borderRadius: 2, overflow: 'hidden' }}>
            <iframe
              src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.811559902302!2d105.93818311540199!3d20.985929986021655!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135a1a1f5928f09%3A0x633d2fc1a11db9d9!2zVmluaG9tZXMgT2NlYW4gUGFyayBHaWEgTMOibQ!5e0!3m2!1svi!2s!4v1689000000000!5m2!1svi!2s"
              width="100%"
              height="100%"
              style={{ border: 0 }}
              allowFullScreen={false}
              loading="lazy"
              referrerPolicy="no-referrer-when-downgrade"
            ></iframe>
          </Box>
        </Box>
      </Box>

      {/* Copyright */}
      <Box
        sx={{
          borderTop: `1px solid ${PALETTE.SURFACE_LIGHT}`,
          pt: 2,
        }}
      >
        <Typography
          sx={{
            fontWeight: 600,
            fontSize: '1.125rem',
            lineHeight: '26px',
            color: PALETTE.BACKGROUND_DEFAULT,
            textAlign: 'left'
          }}
        >
          © 2026 - Realestate. All rights reserved.
        </Typography>
      </Box>
    </Box>
  );
};

export default Footer;
