// MBQC - Angular/src/app/components/common/navbar/navbar.component.ts
import { Component, ChangeDetectionStrategy, signal } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NavbarComponent {
  readonly navItems = ['GIỚI THIỆU', 'DỰ ÁN', 'TIN TỨC'];
  readonly mobileOpen = signal(false);

  toggleMobileMenu() {
    this.mobileOpen.update(v => !v);
  }
}

<header class="navbar-header">
  <div class="navbar-container">
    <!-- Logo -->
    <div class="logo-wrapper">
      <img src="/logo.png" alt="Realestate Logo" class="logo-img" />
    </div>

    <!-- Desktop Menu -->
    <nav class="desktop-nav">
      @for (item of navItems; track item) {
        <a class="nav-link">{{ item }}</a>
      }
    </nav>

    <!-- Right Side -->
    <div class="right-actions">
      <!-- Online Counter -->
      <div class="online-counter">
        <span class="pulse-dot"></span>
        <span class="counter-text">100 người đang Online</span>
      </div>

      <!-- User Profile Circle -->
      <div class="profile-circle">
        <span class="user-icon">👤</span>
      </div>

      <!-- Mobile Menu Toggle Button -->
      <button type="button" class="mobile-toggle" (click)="toggleMobileMenu()" aria-label="Mở menu">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-menu"><line x1="4" x2="20" y1="12" y2="12"/><line x1="4" x2="20" y1="6" y2="6"/><line x1="4" x2="20" y1="18" y2="18"/></svg>
      </button>
    </div>
  </div>

  <!-- Mobile Dropdown Menu -->
  @if (mobileOpen()) {
    <div class="mobile-menu-dropdown">
      @for (item of navItems; track item) {
        <a class="mobile-nav-link" (click)="toggleMobileMenu()">{{ item }}</a>
      }
      <div class="mobile-online-counter">
        <span class="pulse-dot"></span>
        <span class="counter-text">100 người đang Online</span>
      </div>
    </div>
  }
</header>

// train1-figma-bootstrap/src/components/Layout/Navbar.tsx
import { useState } from 'react';
import { motion } from 'framer-motion';
import { Menu } from 'lucide-react';
import NavbarDrawer from './NavbarDrawer';
import { PALETTE } from '../../theme';

interface NavItem {
  id: string;
  label: string;
}

const NAV_ITEMS: NavItem[] = [
  { id: 'intro', label: 'GIỚI THIỆU' },
  { id: 'projects', label: 'DỰ ÁN' },
  { id: 'news', label: 'TIN TỨC' },
];

const Navbar = () => {
  const [mobileOpen, setMobileOpen] = useState(false);

  const handleDrawerToggle = () => {
    setMobileOpen((prevState) => !prevState);
  };

  return (
    <header className="navbar-custom d-flex align-items-center justify-content-between">
      {/* Logo */}
      <motion.div
        className="d-flex align-items-center gap-2 cursor-pointer"
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
      >
        <img
          src="/logo.png"
          alt="Realestate Logo"
          className="navbar-logo"
        />
      </motion.div>

      {/* Desktop Menu */}
      <nav className="d-none d-md-flex align-items-center gap-4" role="menubar">
        {NAV_ITEMS.map((item) => (
          <motion.button
            key={item.id}
            type="button"
            role="menuitem"
            className="nav-link-custom border-0 bg-transparent"
            whileHover={{ color: PALETTE.PRIMARY, y: -2 }}
            transition={{ type: 'spring', stiffness: 300 }}
          >
            {item.label}
          </motion.button>
        ))}
      </nav>

      {/* Right side - Online counter & User Icon */}
      <div className="d-flex align-items-center gap-2 gap-sm-4">
        <div className="d-none d-sm-flex align-items-center gap-2">
          <motion.div
            className="online-dot"
            animate={{
              scale: [1, 1.5, 1],
              opacity: [1, 0.5, 1],
            }}
            transition={{
              duration: 2,
              repeat: Infinity,
              ease: 'easeInOut',
            }}
          />
          <span className="text-caption text-secondary">
            100 người đang Online
          </span>
        </div>

        <motion.button
          type="button"
          className="user-avatar border-0"
          whileHover={{ scale: 1.1, backgroundColor: PALETTE.PRIMARY }}
          whileTap={{ scale: 0.9 }}
          aria-label="Thông tin tài khoản"
        >
          <span style={{ fontSize: '1.25rem' }}>👤</span>
        </motion.button>

        {/* Mobile Menu Toggle */}
        <button
          className="mobile-menu-btn d-md-none"
          onClick={handleDrawerToggle}
          aria-label="Mở menu"
        >
          <Menu size={24} />
        </button>
      </div>

      {/* Mobile Drawer */}
      <NavbarDrawer
        open={mobileOpen}
        onClose={handleDrawerToggle}
        navItems={NAV_ITEMS}
      />
    </header>
  );
};

export default Navbar;
